#!/bin/sh

while read line; do
    message="${message}${line}"
done < ${1}

# adding commit, which contains less than 10 characters and 2 words or contains russian symbols, restriction.
if [ ${#message} -le 10 ]; then
    echo "Commit messages could not be less than 10 characters."
    echo "The following commit message has ${message} characters."
    exit 1
fi

# adding commit, which contains less than 10 characters and 2 words or contains russian symbols, restriction.
quantity="$(echo $message | grep '[[:alnum:]][[:space:]][[:alnum:]]')"
if [ ${#quantity} == 0 ]; then
    echo "Commit messages could contain not less than 2 words."
    exit 1
fi

# adding commit, which contains less than 10 characters and 2 words or contains russian symbols, restriction.
rus="$(echo $message | grep '[а-яё№]')"
if [ ${#rus} -gt 0 ]; then
    echo "Commit messages could not contain russian symbols."
    echo "${message}"
    exit 1
fi

exit 0
